_BASE_: "../mask_rcnn_R_50_FPN_3x_gn.yaml"
MODEL:
  MASK_ON: False
  WEIGHTS: ""
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 512
    NUM_CLASSES: 5
DATALOADER:
  NUM_WORKERS: 2
SOLVER:
  STEPS: []
  MAX_ITER: 60000
  WARMUP_ITERS: 1000
  GAMMA: 0.05
  BASE_LR: 0.00025
  IMS_PER_BATCH: 2
  CHECKPOINT_PERIOD: 2000
TEST:
  EVAL_PERIOD: 500
    
    

