_BASE_: "mask_rcnn_X_101_32x8d_FPN_3x_publaynet.yaml"
MODEL:
  WEIGHTS: "https://www.dropbox.com/s/57zjbwv6gh3srry/model_final.pth?dl=1"
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 64
    NUM_CLASSES: 5
DATASETS:
  TRAIN: ("train_data",)
  TEST: ("val_data",)
DATALOADER:
  NUM_WORKERS: 1
SOLVER:
  STEPS: []
  MAX_ITER: 60000
  WARMUP_ITERS: 1000
  GAMMA: 0.05
  BASE_LR: 0.00025
  IMS_PER_BATCH: 1
  CHECKPOINT_PERIOD: 2000
TEST:
  EVAL_PERIOD: 500
    
    

