_BASE_: "../mask_rcnn_R_50_FPN_3x.yaml"
MODEL:
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ANCHOR_GENERATOR:
    ASPECT_RATIOS:
    - - 1.0
      - 5.0
      - 15.0
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 512
    NMS_THRESH_TEST: 0.7
    NUM_CLASSES: 5
DATASETS:
  TRAIN: ("train_data",)
  TEST: ("val_data",)
INPUT:
  MAX_SIZE_TEST: 1247
  MAX_SIZE_TRAIN: 1247
  MIN_SIZE_TEST: 743
  MIN_SIZE_TRAIN: (743,)
DATALOADER:
  NUM_WORKERS: 2
SOLVER:
  STEPS: []
  MAX_ITER: 60000
  BASE_LR: 0.00025
  IMS_PER_BATCH: 2
  CHECKPOINT_PERIOD: 2000
TEST:
  EVAL_PERIOD: 500
    
    

