_BASE_: "../DLA_mask_rcnn_X_101_32x8d_FPN_3x.yaml"
MODEL:
  WEIGHTS: ("/home/server/Documents/layout/layoutanalysis/diff_models/model_maskrcnn_publaynet_finetuned.pth")
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 64
    NUM_CLASSES: 5
DATASETS:
  TRAIN: ("train_data",)
  TEST: ("val_data",)
DATALOADER:
  NUM_WORKERS: 1
SOLVER:
  STEPS: (100, 150)
  MAX_ITER: 20000
  WARMUP_ITERS: 1000
  GAMMA: 0.05
  BASE_LR: 0.00025
  IMS_PER_BATCH: 1
  CHECKPOINT_PERIOD: 2000
TEST:
  EVAL_PERIOD: 500
    
    

